perses/plugins

- GaugeChart/package.json
- MarkdownChart/package.json
- Prometheus/package.json
- StatChart/package.json
- StaticListVariable/package.json
- TimeSeriesChart/package.json
This PR refactors the plugin module structure to better match Perses conventions.
> refactor plugin module structure

- BarChart/package.json
- GaugeChart/package.json
- MarkdownChart/package.json
- PieChart/package.json
- Prometheus/package.json
- ScatterChart/package.json
- StatChart/package.json
- StaticListVariable/package.json
- StatusHistoryChart/package.json
- Table/package.json
- Tempo/package.json
- TimeSeriesChart/package.json
- TimeSeriesTable/package.json
- TraceTable/package.json
- TracingGanttChart/package.json
- package-lock.json
I am bumping some deps.
While during this, I have noticed sometimes the `@perses-dev` dependencies are in the `dependencies` or in the `peerDependencies`.
@jgbernalp what would be the correct place for them ?
> bump various dependencies

- README.md
Add local plugin development instructions to README
ref. https://github.com/perses/perses/pull/2593
> add local plugin development instructions to README

- prometheus/sdk/cue/filter/filter.cue
- prometheus/sdk/cue/panel/panel.cue
- prometheus/sdk/cue/variable/labelnames/labelnames.cue
- prometheus/sdk/cue/variable/labelvalues/labelvalues.cue
- prometheus/sdk/cue/variable/promql/promql.cue
- prometheus/sdk/cue/variable/variable.cue
- staticlistvariable/sdk/cue/staticlist.cue
Moved from perses/perses (https://github.com/perses/perses/pull/2645)
> Add CUE SDK files

- barchart/rsbuild.config.ts
- package-lock.json
- package.json
- scripts/devserver/devserver.ts
A script to start the dev servers of all plugins in a single Express.js server, allocating a single port.
> Add a single dev server for all plugins

- README.md
Hello,
I felt it would be helpful to add this little caveat I found while setting up the plugins repository for local development.
Not sure if the correct catalog-entry would be DOC or IGNORE in this case so please suggest if otherwise.
> [DOC] Update README.md for plugin local development

- README.md
I used incorrect markdown (which surprisingly used correct in the preview plugin on VSC) but fixing it through this PR.
> [IGNORE] Fix the nested list rendering in README.md

- docs/staticlistvariable/cue/staticlist.md
- docs/staticlistvariable/go/staticlist.md
moved from perses/perses.
The Go doc still has to be enriched, to be tackled later
> [DOC] add DaC docs for staticlistvariable

- scripts/cue-publish/cue-publish.go
- scripts/release/release.go
- scripts/tag/tag.go
- scripts/upload-archive/upload-archive.go
there is an issue when uploading the archive to the github release, and there error message is not explanatory.
I hope like that I will be able to understand what's happening
> catch stderr for all command run

- .github/workflows/ci.yml
this update includes a fix for the release as the archive built will contain the version as before.
> update cli version

- scripts/build-plugin/build-plugin.go
rsbuild sometimes is stuck when building the plugin. I am adding a timeout so it can stop the CI quickly
> add a timeout for each plugin built

- prometheus/src/model/api-types.ts
- prometheus/src/plugins/prometheus-time-series-query/get-time-series-data.ts
- timeseriestable/src/DataTable.tsx
- timeseriestable/src/SeriesName.tsx
Fixing error when querying histograms. Related to https://github.com/perses/perses/pull/2858
> [BUGFIX] Fixing histograms display

- .github/workflows/ci.yml
- README.md
- scripts/cue-publish/cue-publish.go
Same as https://github.com/perses/perses/pull/2867
> [ENHANCEMENT] Remove the `cue login` step

- tempo/src/components/index.ts
Required to use the syntax highlighting and auto-completion in the embedded use case.
> [IGNORE] Tempo: export TraceQLExtension

- barchart/src/BarChartBase.tsx
- barchart/src/BarChartPanel.tsx
Migrate BarChart, rename to BarChartBase
https://github.com/perses/perses/blob/v0.51.0-beta.1/ui/components/src/BarChart/BarChart.tsx
> [IGNORE] Migrate bar chart component

- gaugechart/src/GaugeChartBase.tsx
- gaugechart/src/GaugeChartPanel.tsx
Migrate GaugeChart, rename to GaugeChartBase
https://github.com/perses/perses/blob/v0.51.0-beta.1/ui/components/src/GaugeChart/GaugeChart.tsx
> [IGNORE] Migrate gauge chart component

- piechart/src/PieChartBase.tsx
- piechart/src/PieChartPanel.tsx
Migrate PieChart, rename to PieChartBase
https://github.com/perses/perses/blob/v0.51.0-beta.1/ui/components/src/PieChart/PieChart.tsx
> [IGNORE] Migrate pie chart component

- RELEASE.md
- statchart/package.json
Changelog:
- https://github.com/perses/plugins/pull/134
> [IGNORE] StatChart: prepare release 0.7.0

- RELEASE.md
- package-lock.json
- statushistorychart/package.json
Changelog:
- https://github.com/perses/plugins/pull/133
> [IGNORE] StatusHistoryChart: prepare release 0.7.0

- package-lock.json
- timeseriestable/package.json
TimeSeriesTable now depends on Histogram Panel for displaying native histograms
> [IGNORE] TimeseriesTable: prepare release 0.7.0

- histogramchart/package.json
- histogramchart/sdk/go/histogram.go
- histogramchart/sdk/go/options.go
- package-lock.json
Thanks @jgbernalp & @Nexucis for the tip, removing `"private": true` blocking releasing to npm
> [IGNORE] histogramchart: add Go SDK + prepare release 0.7.1

- timeserieschart/src/TimeSeriesChartBase.tsx
- timeserieschart/src/TimeSeriesChartPanel.tsx
- timeserieschart/src/index.ts
Move the TimeSeriesChart specific code from `@perses-dev/components` to the plugin.
> [IGNORE] Migrate time series chart component

- RELEASE.md
- package-lock.json
- timeserieschart/package.json
- https://github.com/perses/plugins/pull/146
> Prepare timeserieschart release v0.8.0

- timeserieschart/src/TimeSeriesChartBase.tsx
Bring back [this feature](https://github.com/perses/perses/pull/2935) lost with the repo migration.
> [ENHANCEMENT] TimeSeriesChart: support enableSyncGrouping from useChartsContext()

- package-lock.json
> [IGNORE] regenerate package-lock

- datasourcevariable/schemas/datasource.cue
- histogramchart/schemas/histogram.cue
- prometheus/schemas/prometheus-label-values/prometheus-label-values.cue
- prometheus/schemas/prometheus-promql/prometheus-promql.cue
- staticlistvariable/schemas/static-list.cue
- table/schemas/table.cue
- tempo/schemas/tempo-trace-query/query.cue
- timeserieschart/schemas/time-series.cue
- Prevent empty strings for required attributes ([ref](https://github.com/perses/perses/issues/3014#issuecomment-2966507092))
- Enforce max >= min where applicable
- ~[ ] Take the opportunity of this PR to bring back the json-based unit tests for schemas~ to be made generic for external reuse via the CLI, see https://github.com/perses/perses/issues/3018
> [ENHANCEMENT] Improve schema constraints in multiple plugins

- tempo/schemas/tempo-trace-query/query.cue
Fixing validation issue with Tempo `limit` field when saving panel using Tempo datasource.
Before, when saving dashboard:
> [BUGFIX] tempo: fixing limit validation

- package-lock.json
- tempo/package.json
- tracingganttchart/package.json
Bump Tempo and TracingGanttChart
> [IGNORE] Bump Tempo and TracingGanttChart

- piechart/schemas/pie.cue
- piechart/src/PieChartBase.tsx
- piechart/src/PieChartOptionsEditorSettings.tsx
- piechart/src/PieChartPanel.tsx
- piechart/src/utils.ts
- statushistorychart/src/StatusHistoryChartOptionsEditorSettings.tsx
- timeserieschart/src/TimeSeriesChartOptionsEditorSettings.tsx
> ⚠️ To merge this PR, https://github.com/perses/perses/pull/3162 should be merged first, otherwise it can not be built!
Details can be found here
https://github.com/perses/perses/pull/3162
Relates to https://github.com/perses/perses/issues/2787
> [BUGFIX] Filter and user legend values

- piechart/src/PieChartPanel.tsx
Closes https://github.com/perses/perses/issues/3156
Closes https://github.com/perses/perses/issues/2787
This PR adds the multi-column feature to the Pie-Chart Legend Table. So far, the table has had a single column to show the legend label. With this change, based on the selected legend values, table columns are added/removed. 
1. Create a Pie-Chart
2. Go to edit panel > Settings > Legend
3. Add/Remove Legend Values
4. Save your changes
5. Your changes should reflect in the panel
> [BUGFIX] Add multi-column feature to the piechart legend table

- tracingganttchart/src/PanelActions.tsx
- tracingganttchart/src/TracingGanttChart/DetailPane/Attributes.tsx
- tracingganttchart/src/TracingGanttChart/DetailPane/SpanLinks.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/SpanLinksButton.tsx
- tracingganttchart/src/TracingGanttChart/utils.ts
use new replaceVariablesInString utility which landed in https://github.com/perses/perses/pull/3210
no UI changes
> [IGNORE] TracingGanttChart: use new replaceVariablesInString utility

- docs/prometheus/README.md
To be added to the "User docs" part of the website. 
> [DOC] Prometheus: add user doc

- docs/prometheus/README.md
> [IGNORE] Fix typo in doc

- docs/prometheus/README.md
> [IGNORE] fix prom doc formatting

- package-lock.json
- tempo/package.json
- tracetable/package.json
- tracingganttchart/package.json
bump Tempo, TraceTable and TracingGanttChart
no UI changes
> [IGNORE] bump Tempo, TraceTable and TracingGanttChart

- flamechart/package.json
- package-lock.json
- pyroscope/package.json
> [IGNORE] Prepare pyroscope and flamechart release 0.3.0

- timeserieschart/schemas/migrate/migrate.cue
- timeserieschart/schemas/migrate/tests/basic/expected.json
- timeserieschart/schemas/migrate/tests/basic/input.json
- timeserieschart/schemas/migrate/tests/byregexp-colors/expected.json
- timeserieschart/schemas/migrate/tests/byregexp-colors/input.json
> [ENHANCEMENT] TimeSeriesChart: migration: Y axis: support label + new data model for min & max

- prometheus/src/explore/PrometheusMetricsFinder/PrometheusMetricsFinder.tsx
- prometheus/src/explore/PrometheusMetricsFinder/filter/FilterInputs.tsx
Filter without value will not be take in account for data displayed + better handling when changing operator.
> [ENHANCEMENT] prometheus: improve explorer filters
