- MarkdownChart/rsbuild.config.ts
It might break things in Perses, but not something that is impossible to fix.
> fix markdown chart name in rsbuild

- .github/workflows/ci.yml
- scripts/build-archive/build-archive.go
Putting back in the archive a list of files and folders require to be a valid plugin.
I am also adding the the folder `cue.mod` and `schemas` that will be required later in the backend to allow the plugin in the database.
> put back list of files in the final build archive and add cue.mod folder

- .github/workflows/ci.yml
the cue dependencies required to make the schema working are missing in the archive built.
I'm changing the order of the job in the CI so the cuelang dependencies are installed before building the archive
> install cue dependencies before building the archive

- Prometheus/package.json
- Prometheus/src/components/PromQLEditor.tsx
- Table/package.json
- Table/src/CellsEditor/CellEditor.tsx
- Table/src/ColumnsEditor/ColumnEditorContainer.tsx
- TraceTable/package.json
- TraceTable/src/DataTable.tsx
- package-lock.json
This PR:
- bumps a new version of the Prometheus plugin
- Fixes an issue with federation and material UI Tooltips by adding keys to the components, this fixes e2e tests on https://github.com/perses/perses/pull/2557 see https://github.com/mui/material-ui/issues/34150
> add component keys to fix Perses e2e

- scripts/npm/npm.go
- scripts/release/release.go
I am adding a release script to release the various plugin we have using a simple command line.
Note that you will need to install the [GitHub CLI](https://github.com/cli/cli?tab=readme-ov-file) to use this script.
Usage:
```bash
go run ./scripts/release/release.go --all
go run ./scripts/release/release.go --name=Tempo
go run ./scripts/release/release.go --all --message="Release message"
```
> add a release script

- GaugeChart/src/GaugeChartPanel.tsx
Ref https://github.com/perses/perses/pull/2548
The `GaugeChart` only checks for `undefined`, not `null`, when deciding whether to show the no data display:
https://github.com/perses/perses/blob/c4a7621b138b903599743c7162526a5cbc7cb73e/ui/components/src/GaugeChart/GaugeChart.tsx#L52
> [BUGFIX] GaugeChartPanel: fix empty state

- TimeSeriesChart/package.json
- TimeSeriesChart/schemas/migrate/migrate.cue
- package-lock.json
The previous code with the switch-like statement is strictly equivalent to new one, and it is working fine with Perses "live", no issue to migrate dashboards from the UI etc. but for some reason it is causing this error in the migrate unit tests with the bump to cue v0.12 on perses/perses side: `cue: marshal error: spec.visual.lineWidth: cannot convert incomplete value "_" to JSON.`
Ref https://github.com/perses/perses/pull/2599
> [IGNORE] TimeSeriesChart: mystery fix for perses/perses migration unit tests 

- package-lock.json
- prometheus/package.json
- prometheus/src/components/PromQLEditor.tsx
This PR:
- downgrades the `@prometheus-io/codemirror-promql` to avoid the [auto purge warning](https://github.com/prometheus/prometheus/blob/906f6a33b60cec2596018ac8cc97ac41b16b06b7/web/ui/module/codemirror-promql/src/client/prometheus.ts#L297)
- Adds keys to the buttons on tooltips to make react happy
> downgrade promql code mirror to avoid warning, add keys to tooltip buttons

- .github/workflows/ci.yml
- scripts/build-archive/build-archive.go
- scripts/npm/npm.go
- scripts/release/release.go
- scripts/upload-archive/upload-archive.go
This PR is fixing the way to release the plugin and the way to upload the archive that has been broken after #50 was merged
It will change the release name convention. Before this PR, the tag release was following the pattern `PluginName-X.Y.Z`.
Now the pattern is `pluginFolderName/vX.Y.Z`. This is to be compliant with the golang submodule versioning. Doing that will allow user to get the plugins like that:
```bash
go get github.com/perses/plugins/prometheus@v0.5.1
```
> update the way to release to be compliant with golang and submodules

- prometheus/src/explore/PrometheusMetricsFinder/overview/MetricOverview.tsx
- prometheus/src/explore/PrometheusMetricsFinder/overview/tabs/OverviewTab.tsx
- prometheus/src/explore/PrometheusMetricsFinder/utils.ts
Fixing issue: https://github.com/perses/perses/issues/2534
Improve display when there a request fail to fetch data in overview tab
Metadata request failing:
Series request failing:
Both:
See [Storybook](https://github.com/perses/perses/tree/main/ui/storybook#visual-tests)
and [e2e](https://github.com/perses/perses/tree/main/ui/e2e#visual-tests) docs for more details. Common issues
include:
- Is the data inconsistent? You need to mock API requests.
- Does the time change? You need to use consistent time values or mock time utilities.
- Does it have loading states? You need to wait for loading to complete.
> [ENHANCEMENT] Metric finder: improve error displays

- tracetable/src/TraceTablePanel.tsx
The explorer param changed from `traces` to `Tempo-TempoExplorer`.
> Fix default trace table link

- .github/workflows/ci.yml
- .github/workflows/pr.yml
CUE Central Registry login does not work on forks because GitHub Secret is not available.
cc @AntoineThebaud @Nexucis
> [IGNORE] Use separate CI pipeline for PRs due to missing CUE token on PRs

- table/schemas/table.cue
- table/src/ColumnsEditor/ColumnEditor.tsx
- table/src/TablePanel.test.tsx
- table/src/TablePanel.tsx
- table/src/table-model.ts
Support custom units per table column.
**This PR depends on https://github.com/perses/plugins/pull/86**
Resolves: https://github.com/perses/perses/issues/2455
> [ENHANCEMENT] Table: support custom units

- tempo/src/model/tempo-client.ts
Instead of a technical error, let's show "Invalid response from server" if the server sends invalid JSON. The actual error message is logged to the JS console.
Before:
After:
> Tempo: improve error message if server returns invalid JSON

- .github/workflows/ci.yml
the cue version is not the correct one for the release. See https://github.com/perses/plugins/actions/runs/13968911933/job/39106844660
> upgrade cue version for the release

- table/sdk/go/table.go
This commit ports the sort and format options in Table columnSettings, from Cue to Go SDK.
> [BUGFIX]: Add sort and format options from Table cue to go-sdk

- tempo/src/components/complete.ts
- tempo/src/model/api-types.ts
The Tempo API omits empty string values in the response: https://github.com/grafana/tempo/blob/d1286af14613dd9b5da65f35b474b17895fb4be6/pkg/tempopb/tempo.pb.go#L1755
Fixed the response type and handled this case in the auto-completion.
no UI changes
> [BUGFIX] Tempo: Fix auto-completion with empty string values

- piechart/schemas/pie.cue
- piechart/src/PieChartPanel.tsx
- piechart/src/palette-gen.ts
- piechart/src/pie-chart-model.ts
Closes https://github.com/perses/perses/issues/2786. Technically a breaking change but shouldn't cause any issue anyway since these attributes were completely useless here.
(No impact)
> [BREAKINGCHANGE] PieChart: remove useless attributes

- prometheus/package.json
- tempo/rsbuild.config.ts
- tracetable/package.json
- tracingganttchart/package.json
- tracingganttchart/rsbuild.config.ts
Almost any version of react-router-dom should be suitable for the use cases in the Prometheus, TraceTable and TracingGanttChart plugins.
> [IGNORE] Relax react-router-dom dependency constraints

- package-lock.json
- tracetable/package.json
relax @mui/x-data-grid dependency requirement, because v7.21.0 introduced a bug: https://github.com/mui/mui-x/issues/17428
no visible UI changes
> [IGNORE] relax @mui/x-data-grid dependency requirement

- tempo/src/model/tempo-client.test.ts
- tempo/src/model/tempo-client.ts
Sanitize search params, i.e. do not send `?param=undefined` to the Tempo API.
no UI changes
> [BUGFIX] Tempo: cleanup search params in API calls

- tempo/src/components/TraceQLEditor.tsx
- tempo/src/components/TraceQLExtension.ts
- tempo/src/components/complete.ts
- tempo/src/plugins/tempo-trace-query/TempoTraceQueryEditor.tsx
Tempo TraceQL Editor: account for selected time range for auto-completions.
Otherwise, by default, only tag values of the last 15 minutes or so are shown.
no UI changes
> [ENHANCEMENT] Tempo TraceQL Editor: account for selected time range for auto-completions

- package-lock.json
- piechart/src/PieChartBase.tsx
- prometheus/package.json
- prometheus/src/plugins/index.ts
- timeserieschart/package.json
- timeserieschart/src/index.ts
This PR adds missing exports for prometheus and time series chart plugins. Bumps its versions for a new release with these fixes.
> [BUGFIX] fix plugin exports

- barchart/package.json
- datasourcevariable/package.json
- gaugechart/package.json
- histogramchart/package.json
- markdown/package.json
- package-lock.json
- piechart/package.json
- prometheus/package.json
- scatterchart/package.json
- statchart/package.json
- statchart/src/StatChartBase.tsx
- staticlistvariable/package.json
- statushistorychart/package.json
- table/package.json
- tempo/package.json
- timeserieschart/package.json
- timeseriestable/package.json
- tracetable/package.json
- tracingganttchart/package.json
- bump to latest Perses
- cleanup dependencies (remove @perses-dev dependencies in dependencies section; some plugins had them as a workaround to use features from a snapshot release)
supersedes https://github.com/perses/plugins/pull/131
> [IGNORE] bump to latest Perses, cleanup dependencies

- datasourcevariable/rsbuild.config.ts
Port 3012 already used by staticlistvariable plugin
> [IGNORE] datasourcevariable: change default port

- table/sdk/go/table.go
Importing JSON for table panel kind with empty format for the columns throws invalid panel error
```
"columnSettings": [
{
"name": "cluster",
"header": "Cluster",
"format": {
"unit": ""
},
"align": "right"
},
```
`bad request: invalid panel 0_0: spec.columnSettings.0.format: 11 errors in empty disjunction: spec.columnSettings.0.format.unit: 8 errors in empty disjunction: spec.columnSettings.0.format.unit: conflicting values "bytes" and "": 1:77 ../plugins/Table-0.7.1/cue.mod/pkg/github.com/perses/perses/cue/common/format.cue:35:18 spec.columnSettings.0.format.unit: conflicting values "days" and "": 1:77 ../plugins/Table-0.7.1/cue.mod/pkg/github.com/perses/perses/cue/common/format.cue:19:69 spec.columnSettings.0.format.unit: conflicting values "decimal" and "": 1:77 …
> [BUGFIX] make Format field a pointer to keep optional

- prometheus/src/components/TreeNode.tsx
Closes https://github.com/perses/perses/issues/3133
As suggested here (https://github.com/perses/perses/issues/3133), the response time is simply rounded using `Math.round` function. 
To test this you need to run the Perses/Plugin localy
- Clone the Repo
- Swith to this branch
- Have the Perses CLI ready on your machine, and then:
-  ./percli.exe plugin start ../../../projects/plugins/prometheus/
- You also need to run the server and client of Perses itself
> [FEATURE] prometheus: Round the promql response time

- prometheus/src/plugins/prometheus-time-series-query/get-time-series-data.ts
Closes https://github.com/perses/perses/issues/2362
If the selected range of the time-series is shorter than the step, 
The `start` and `end` would be rounded to the same value. Consequently, the time range would be zero.
If the time range is set to zero, the X-Axis scale would not show the proper information. The query also would not be correct, because the range is zero.
This change set the end accordingly to make sure there would be always a valid time range.
> [BUGFIX] Set the end of the time range according to the start and step

- prometheus/src/explore/PrometheusMetricsFinder/filter/FinderFilters.tsx
Perses Explorer -> Finder tab allows to search for metrics while specifying a datasource but the dropdown is no wide enough for good UX
Current
Expected
> [ENHANCEMENT] Explore view -> Finder tab datasource dropdown

- statchart/src/utils/get-color.ts
@AntoineThebaud 
Closes https://github.com/perses/perses/issues/3142
Details of the bug can be found here https://github.com/perses/perses/issues/3142
JS, the most lovely programming language in the world, equates `0` with `false`. Therefore, developers should be careful with their conditional statements. Since JS considers 0 to be false, if it makes sense for the given scenario, `typeof` should be used instead. 
For more information you can take a look at the following MDN link. 
https://developer.mozilla.org/en-US/docs/Glossary/Falsy
> [BUGFIX] Fix statchar color for zero values

- package-lock.json
- prometheus/package.json
- tempo/package.json
this bump will release the datasource that includes the fix related to the datasource variable.
See https://github.com/perses/perses/issues/3084 for more info about the bug and https://github.com/perses/perses/pull/3111 for the fix in the cuelang common package
> [ignore] bump prometheus and tempo to v0.52.1

- package-lock.json
- timeserieschart/package.json
- timeserieschart/src/CSVExportUtils.ts
- timeserieschart/src/TimeSeriesChart.ts
- timeserieschart/src/TimeSeriesExportAction.tsx
- timeserieschart/src/index.ts
This PR implements the CSV export functionality for the TimeSeriesChart plugin, working in conjunction with the core changes in perses/perses to enable CSV downloads for time series data. File gets downloaded with name "panelName_data.csv".
Adds an "Export as CSV" action button to TimeSeriesChart panels that allows users to download their time series data in CSV format. The export includes proper column headers (using legend names when available) and formats timestamps in ISO 8601 format for Excel and Sheets compatibility.
* **TimeSeriesExportAction component**: Renders the download button and handles CSV generation
* **CSV export utilities**: Functions for data formatting, filename sanitization, and CSV generation
* **Plugin integration**: Adds export action to TimeSeriesChart plugin …
> [FEATURE] Add CSV export functionality for TimeSeriesChart plugin

- tempo/src/plugins/tempo-trace-query/get-trace-data.ts
- tracingganttchart/src/TracingGanttChart/DetailPane/DetailPane.tsx
- tracingganttchart/src/TracingGanttChart/DetailPane/SpanLinks.test.tsx
- tracingganttchart/src/TracingGanttChart/DetailPane/SpanLinks.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/GanttTable.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/GanttTableRow.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/SpanLinksButton.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/SpanName.tsx
- tracingganttchart/src/TracingGanttChart/TracingGanttChart.tsx
- tracingganttchart/src/TracingGanttChart/trace.test.ts
- tracingganttchart/src/TracingGanttChart/trace.ts
- tracingganttchart/src/test/traces/example_otlp.json
Show span links next to the span name and in the detail pane.
Link icon next to span name:
If there are multiple links, show a menu:
Span link details in the attribute pane:
> [FEATURE] TracingGanttChart: show span links

- prometheus/src/components/TreeNode.tsx
Closes https://github.com/perses/perses/issues/3219
Simply manages very long text in PromQl tree tooltip
Do the following trick 
```typescript
{escapeString(value)+'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
```
> [BUGFIX] Handle long text in promql tree view tooltip

- table/schemas/migrate/migrate.cue
- timeserieschart/schemas/migrate/migrate.cue
- timeserieschart/schemas/migrate/tests/basic-2/expected.json
- timeserieschart/schemas/migrate/tests/basic/expected.json
- timeserieschart/schemas/migrate/tests/legacy-panel/expected.json
- simplify some code in table migration logic
- avoid generating an empty array for querySettings
- formatting for Table & TimeSeriesChart
- add note for future work for Table
> [IGNORE] some migration patches

- prometheus/src/plugins/prometheus-variables.tsx
- tempo/src/plugins/tempo-trace-query/TempoTraceQueryEditor.tsx
Closes https://github.com/perses/perses/issues/3265
Details of the bug can be found in the issue
Changes of the prometheus\src\plugins\prometheus-variables.tsx had not been tracked. Consequently, clicking on the Run Query Button would eliminate the dangling state of the controls. 
> [BUGFIX] Prometheus: Track the changes of variable

- tracingganttchart/src/PanelActions.tsx
- tracingganttchart/src/TracingGanttChart/GanttTable/SpanLinksButton.tsx
Returning undefined is only supported in React 18+, and will throw an error in React 17.
https://github.com/reactwg/react-18/discussions/75
no UI changes
> [IGNORE] TracingGanttChart: return null instead of undefined in React components

- prometheus/package.json
> [BUGFIX] Prometheus: fix diplay names of variable plugins

- prometheus/src/plugins/prometheus-variables.tsx
- staticlistvariable/src/StaticListVariable.tsx
>⚠️ SHOULD BE REVIEWED AND TESTED WITH https://github.com/perses/perses/pull/3298
Closes https://github.com/perses/perses/issues/3283
Details can be found in the corresponding issue https://github.com/perses/perses/issues/3283
This PR removes direct specification update by the label and matcher inputs. Only data source change is allowed to update the spec directly. 
> ⚠️ To test this PR you need to attach to the **Prometheus** Plugin using `Perses CLI Plugin Start Command`
> ⚠️ To test this PR you need to attach to the **StaticListVariable** Plugin using `Perses CLI Plugin Start Command`
1. Try to **create/update** variables
2. Interaction with Label Name should not make any request to the backend (Check the network tab)
3. Interaction with the matchers should not make any request to the …
> [BUGFIX] Interaction with controls should not update spec directly

- prometheus/src/components/PromQLEditor.tsx
- prometheus/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
Relates to https://github.com/perses/perses/issues/3218
>⚠️ This PR only covers the Plugin Side - Prometheus. There will be a PR for Perses/Perses as well
> ⚠️ There will be  separate PRs for the Temp as well
Quick Query Viewer controls should be read-only. Otherwise, it may make confusion for the users. 
> [ENHANCEMENT] Disable Prometheus query editor controls accordingly

- tracingganttchart/src/TracingGanttChart/DetailPane/DetailPane.tsx
Added the number of events or links in the tab. Easier to see if a span has a lot of events or links.
> [ENHANCEMENT] tracingganttchart: add number of events and links in tab

- prometheus/src/plugins/prometheus-time-series-query/PrometheusTimeSeriesQueryEditor.tsx
Fixing readonly inputs for prometheus query editor. This dialog need to use Perses Dialog component.
BEFORE:
AFTER:
> [BUGFIX] prometheus: query-editor: use readonly instead of disabled prop

- scripts/release/changelog.go
Handle exit error of gh command to handle new plugin change logs
> [IGNORE] fix previous tag script to account for new plugins

- timeserieschart/schemas/migrate/migrate.cue
- timeserieschart/schemas/migrate/tests/basic-3/expected.json
- timeserieschart/schemas/migrate/tests/basic-3/input.json
- timeserieschart/schemas/migrate/tests/basic/expected.json
- timeserieschart/schemas/migrate/tests/basic/input.json
- timeserieschart/schemas/migrate/tests/byregexp-colors/expected.json
- timeserieschart/schemas/migrate/tests/color-based-on-legend-text/expected.json
- timeserieschart/schemas/migrate/tests/color-based-on-legend-text/input.json
Grafana migration logic improvements corresponding to https://github.com/perses/plugins/pull/347 & https://github.com/perses/plugins/pull/386.
> [ENHANCEMENT] TimeSeriesChart: migration: support lineStyle & opacity override

- barchart/rsbuild.config.ts
- clickhouse/rsbuild.config.ts
- datasourcevariable/rsbuild.config.ts
- flamechart/rsbuild.config.ts
- gaugechart/rsbuild.config.ts
- heatmapchart/rsbuild.config.ts
- histogramchart/rsbuild.config.ts
- loki/rsbuild.config.ts
- markdown/rsbuild.config.ts
- piechart/rsbuild.config.ts
- prometheus/rsbuild.config.ts
- pyroscope/rsbuild.config.ts
- scatterchart/rsbuild.config.ts
- statchart/rsbuild.config.ts
- staticlistvariable/rsbuild.config.ts
- statushistorychart/rsbuild.config.ts
- table/rsbuild.config.ts
- tempo/rsbuild.config.ts
- timeserieschart/rsbuild.config.ts
- timeseriestable/rsbuild.config.ts
- tracetable/rsbuild.config.ts
- tracingganttchart/rsbuild.config.ts
This PR implements [the changes that were suggested](https://github.com/perses/perses/pull/3377#issuecomment-3317888993) by @jgbernalp suggested that the publicPath in the plugins can be defined through the module federation configuration.
Follow on from #391
> [ENHANCEMENT] add getPublicPath function to all plugins

- clickhouse/rsbuild.config.ts
Add missing LICENSE file to clickhouse plugin, this is required for publishing as an npm package
> [IGNORE] add missing license to clickhouse plugin

- gaugechart/schemas/migrate/migrate.cue
- gaugechart/schemas/migrate/tests/basic/expected.json
- statchart/schemas/migrate/migrate.cue
- statchart/schemas/migrate/tests/basic/expected.json
- statchart/schemas/migrate/tests/mappings/expected.json
- statchart/schemas/migrate/tests/overrides_to_mappings/expected.json
- timeserieschart/schemas/migrate/migrate.cue
- timeserieschart/schemas/migrate/tests/basic/expected.json
- timeserieschart/schemas/migrate/tests/basic/input.json
This bug went unnoticed until then because the common color codes like "red", "green", "blue" are actually well interpreted by the Perses vizualisation in the end. More exotic ones like "semi-dark-yellow" aren't. Anyway the color picker doesn't like these, thus we want in any case to convert to hexa code.
> [BUGFIX] Migration: Fix wrong threshold color value in several plugins
